### ISSUE TITLE
Initial scrypt doesn't work on linux

### ISSUE THREAD

**Issue by ajsenko5** [liyuanhe211/Energy_Diagram_Plotter_CDXML#2]
have everything installed, get an error of:
ModuleNotFoundError: No module named 'Python_Lib.My_Lib_PyQt'
on the first line of the script.

**Comment by liyuanhe211** [comment]
Sorry for the late reply. I don't usually use Linux with GUI. Just got the free time to set up one.

Your original question is easy to solve (I accidentally updated the actual lib files to a link), the new commit will solve that error.

However, the GUI is not rendered correctly, and I'm not sure how to make it work at this time.

So for now, it only works on Windows. If you (or anyone else) got an idea on how to make it work on CentOS, please comment.

**Comment by liyuanhe211** [comment]
OK it's fixed. I tested it on CentOS 8. Please try the new version.
