### ISSUE TITLE
The program does not launch at windows

### ISSUE THREAD

**Issue by misterkura** [liyuanhe211/Energy_Diagram_Plotter_CDXML#4]
Hi developers,

Thank you for writing this very beautiful program. The sad news is I could not test it on my windows 10 computer. I have tried two approaches, one is running the windows .exe version directly. In which case command prompt runs and blinks in 1-2 seconds, then disappears, without opening the program.

My second approach was to install phyton 3.10 from website, downloading Visual Studio for Windows fro website, downloading OpenSSL from a website (not official one, official one was not easy to apply), also the PyQt5 from a youtube video link (I had no proper phyton knowledge to implement the official website guide). The second approach, finally yielded an import error about QT. The Turkish explanation can be translated as "the module could not be found". I have also tried copying the PyQT5 file in the windows download to the phyton computer folder. This did not work as well with a ImportError: bad magic number in 'PyQt5': b'a\r\r\n' message.

I am adding 3 error screenshots as your request. Hope you can find a solution so I can use this beautiful program.

Thanks,
![fail of windows](https://user-images.githubusercontent.com/114594911/192816822-9a8e7e16-b1f9-4b35-a15a-f480d700ea50.png)
![fail of phyton file](https://user-images.githubusercontent.com/114594911/192816837-731d58c6-6587-46da-b409-7f1bcfbaa44e.jpg)
![Windows file PyQT5 to C-Phyton310-Lib folder ](https://user-images.githubusercontent.com/114594911/192816842-3906bd7a-8f99-4f93-94ba-9f3f6db73050.png)

**Comment by misterkura** [comment]
Hi, I tried a new approach. I downloaded a compatible Phyton 3.5.0 and Pyqt5. The new error can be found in the picture below. Thanks.
![2022-09-30_15-07-35](https://user-images.githubusercontent.com/114594911/193266598-1f89cbf4-d262-4def-adfb-5c9f1bf84834.png)

**Comment by misterkura** [comment]
Hi, sorry for much updates, I took a snapshot for the error that was within the .exe file of "Energy Diagram Plotter CDXML 3.4 (Packed Executable with Python Environment)". As you suggested the other user, I took a snapshot with cmd. Below photo is the photo of two attempts I have commited to open the program. I see no error message. Thanks.

![2022-09-30_15-17-14](https://user-images.githubusercontent.com/114594911/193268278-d6062b17-aa09-40dc-8839-578ebc79f6f8.png)

**Comment by misterkura** [comment]
The issue was partially solved. It was solved by downloading the latest python (3.10.7), installing PyQt5, openpyxl, matplotlib with 

python -m pip install *programname*  command from cmd.

command. I will keep the issue open because, the windows release with phyton environment still does not run.

That being said, the running phyton oriented program seems to be not correctly operating. Almost nowhere is clickable except a very small window ) marked green below (first pictrure). From that window we can implement the excel file to see a plot (picture 2) but some exmaples like example 3, program closes without opening a graph. 

This is the current state and I will open a new issue about this error, because it no longer is in "the program does not launch at windows" category.

![1](https://user-images.githubusercontent.com/114594911/193344734-620de49e-fc1a-439f-9566-4ceb521ce82c.png)

![2](https://user-images.githubusercontent.com/114594911/193344774-2c6c18f8-a63b-43d3-972c-5cb5e27e010f.png)

**Comment by liyuanhe211** [comment]
Please try the new version. It should solve the GUI render problem.
