### ISSUE TITLE
Graphichs and functionality misfunction in Phyton version program

### ISSUE THREAD

**Issue by misterkura** [liyuanhe211/Energy_Diagram_Plotter_CDXML#5]
Hi,  phyton version program seems to be not correctly operating. Almost nowhere is clickable except a very small window ) marked green below (first pictrure). From that window we can implement the excel file to see a plot (picture 2) but some examples like example 3, program closes without opening a graph.

![1](https://user-images.githubusercontent.com/114594911/193345358-70e054cd-0790-4467-8692-71ae68fc433d.png)

![2](https://user-images.githubusercontent.com/114594911/193345222-0299c1d2-d2f2-47ec-8235-0f2fce678ca6.png)

**Comment by liyuanhe211** [comment]
I've updated the script. Please clone the new version and have a try.

**Comment by misterkura** [comment]
Problem is solved. Thank you very much.
