### ISSUE TITLE
Cant open in windows?

### ISSUE THREAD

**Issue by zipo214** [liyuanhe211/Energy_Diagram_Plotter_CDXML#8]
I downloaded the exe version and it just opened a cmd line and closed. 

Edit:
Does the .exe just run and open a GUI? When it opens on my windows 10 pc it opens what appears to be a cmd window and then closes.

should the program .exe be formally added to program files to work?

**Comment by liyuanhe211** [comment]
You should be able to just double click the exe file, and see both a cmd window and the GUI. 

If the cmd window briefly appeared and closed on its own, it's likely that there is an error during the launch process. In that case, you can use the `Use this script to capture the error message if the program crashes.bat` file. By double click that, it should keep the error message, and we can figure it out from there.

It doesn't needs to be in the `C:\Program Files` folder.

**Comment by zipo214** [comment]
Hello,

_At First_: I could not find a > `Use this script to capture the error message if the program crashes.bat` file.  But I tried a bunch of things but then realized I didnt have pyqt6, and was very confused. I was using your 3.4 release not your 3.5 release. On the main page for your repo I did not look to the right side where "Releases" are noted. I went down to the ReadMe displayed section and click on the hyperlinked text that says "the release" which is a static link to your 3.4.1 release which was not working (unsure if you can change that to a dynamic link to be updated to the most recent release, but that was my problem). I was able to find the 3.5 release. I downloaded the 3.5 release and the UI opened. I will report back if there is another issue.

**Comment by liyuanhe211** [comment]
I apologize for forgetting to change the release link. I have changed the link to "/releases/latest" which will dynamically link to the latest release. Thanks for pointing that out. 

Feel free to report any new problems.
