### ISSUE TITLE
Is it possible to provide an exmaple of python interface

### ISSUE THREAD

**Issue by SingletC** [liyuanhe211/Energy_Diagram_Plotter_CDXML#9]
I love this script. It will be very nice if anyone can provide an example of how to use it in python. I will be very helpful for anyone want to use it without GUI

**Comment by liyuanhe211** [comment]
I'm not sure whether I understand what do you need. Could you give an example use case of what you are trying to achieve?

If you wish with to control the GUI with a python script, you can import the Draw_Energy_Diagram_XML_GUI class and access the GUI components with an instance of the class. However I couldn't see a use case of that.

If you wish to create the state/connecting lines with a program, I think it's equally valid just to create an excel input with a program and feed it to my script.
